### ISSUE TITLE
Better guide for moviepy

### ISSUE THREAD

**Issue by jihobak** [udacity/CarND-LaneLines-P1#15] opened 2016-12-17 07:51 UTC
Hi, I'm jiho in Nov cohort.

Even if people finish install moviepy, there might be error when import the library.
because of ffmpeg exe.

![image](https://cloud.githubusercontent.com/assets/10293523/21285333/d2a0bd40-c478-11e6-8ed2-d1da61247420.png)

solution is simple:
install it

![image](https://cloud.githubusercontent.com/assets/10293523/21285336/e6d91758-c478-11e6-95ed-1d4c20cc48ac.png)

So, I thinks it is better to add these to read.md

Thanks

**Comment by ryan-keenan** [comment] 2016-12-17 18:32
Hi Jiho, thanks for reporting this!  Which OS are you on?  I just tried this on my MacBook Pro and got the following error:

`>>> import imageio
>>> imageio.plugins.ffmpeg.download()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'imageio.plugins.ffmpeg' has no attribute 'download'
>>> 
`

**Comment by jihobak** [comment] 2016-12-18 02:29
@ryan-keenan It looks weird..., I used MacBook Pro.
python versions are below
![image](https://cloud.githubusercontent.com/assets/10293523/21291047/240934e0-c515-11e6-8bb9-5f5ae2175877.png)

**Comment by sunnychugh87** [comment] 2016-12-18 23:42
I used above commands on windows 10 anaconda spyder. It worked like charm

**Comment by Hayoung-Kim** [comment] 2016-12-19 01:31
@ryan-keenan Did you import imageio? I saw the same message when I didn't import imageio.

I successfully downloaded needed files when I tried like this:

> import imageio
> imageio.plugins.ffmpeg.download()

**Comment by shivajid** [comment] 2016-12-20 02:08
I had the same issue with Ubuntu 16.04. 

a) Works with what jihobak suggested

I think it would be good to have some introduction to the moviepy library. I had to go and figure out what the library did and the fact that the image was actual a tensor of the image array and not the image path (which may be obvious, but I tripped on it).

**Comment by dcrunch** [comment] 2016-12-21 03:47
i too have same issue and resolved by importing imageio and then running ffmpeg.download command as suggested above.

**Comment by aasaanhai** [comment] 2017-01-23 18:04
I was also facing this issue.  
Env :  Windows 10, Anaconda, Python 3.5,   imageio ( 1.5.0 via menpo) ,  
And I get AttributeError: module 'imageio.plugins.ffmpeg' has no attribute 'download'
Now, after updating the imageio to  ( 2.1.1  via  conda-forge), the issue is resolved.

**Comment by BrandonHe** [comment] 2017-01-24 02:47
Here are my information for you guys reference:
Env: Mac Sierra, 10.12.2

I firstly also got the error info after following the instruction of troubleshooting to resolve the ffmpeg issue by adding these two lines code  in a code cell in the notebook:
```
import imageio
imageio.plugins.ffmpeg.download()

```
Then got below error information:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-8-07cd959207c9> in <module>()
      1 # Import everything needed to edit/save/watch video clips
      2 import imageio
----> 3 imageio.plugins.ffmpeg.download()
      4 from moviepy.editor import VideoFileClip
      5 from IPython.display import HTML

AttributeError: module 'imageio.plugins.ffmpeg' has no attribute 'download'
```

Tried several times, I find the root cause: **Not successfully install the moviepy**
Be sure you really successfully get below information after you run the command
```
CarND-Term1-Starter-Kit$ conda env create -f environment.yml
```
that means installed moviepy successfully:
```
Successfully built moviepy theano pyyaml
Installing collected packages: tqdm, moviepy, protobuf, tensorflow, theano, pyyaml, Keras
  Running setup.py install for Keras ... done
Successfully installed Keras-1.2.1 moviepy-0.2.2.11 protobuf-3.1.0.post1 pyyaml-3.12 tensorflow-0.12.1 theano-0.8.2 tqdm-4.11.2
#
# To activate this environment, use:
# > source activate carnd-term1
#
# To deactivate this environment, use:
# > source deactivate carnd-term1
#
```
Launch the Jupyter notebook, delete added two lines 
``` 
import imageio 
imageio.plugins.ffmpeg.download()
```
Finally , execute with success.

**Comment by Prtfw** [comment] 2017-01-28 17:53
Hey @BrandonHe... I am having the same issue (thanks for figuring this out btw...) 
... do you mind explaining exactly how you got the moviepy to install successfully? (it's currently listed when i run [conda list] but I installed using pip)
thanks lots!

**Comment by BrandonHe** [comment] 2017-01-30 08:04
@Prtfw 
I am not sure you need to configure a proxy, I configured a .bash_profile in home directory, via proxy to download all dependencies and packages needed. 
```
  1 # Set proxy for terminal
  2 export http_proxy="yourproxy.com:port"
  3 export https_proxy="yourproxy.com:port"
  4 # added by Miniconda3 4.2.12 installer
  5 export PATH="/Users/brandon/miniconda3/bin:$PATH"
```
Then run command:
```conda env create -f environment.yml```
After command executes successful, it'll return screen shot like I made:

![carnd-term1](https://cloud.githubusercontent.com/assets/13449160/22415810/1711e64e-e705-11e6-829d-b067de6e82ca.png)

I think using the pip install is also OK. Moviepy is also installed via pip in [environment.yml](https://github.com/udacity/CarND-Term1-Starter-Kit/blob/master/environment.yml). Did you run command  with successful return? The package version should be also considered.

**Closed** 2017-02-19 01:35 UTC

**Comment by SimonAltmannshofer** [comment] 2018-06-29 15:36
For me, the following solution worked:
https://github.com/imageio/imageio/issues/357
