### ISSUE TITLE
The Matplotlib issue in Anaconda environment

### ISSUE THREAD

**Issue by wpiHWzhao** [udacity/CarND-LaneLines-P1#79] opened 2018-10-13 02:08 UTC
The CarND Term1 Starter Kit Anaconda environment only has matplotlib 1.5.3. But matplotlib colors to_rgba requires matplotlib 2.0. Users should update manually.

**Comment by mvirgo** [comment] 2018-11-15 00:05
Thanks for the note - where did you run into this issue? At least for the standard one of `COLOR_BGR2GRAY`, it appears to work fine with the starter kit.

**Comment by mvirgo** [comment] 2018-11-26 17:39
Okay, thanks. Without reproducibility I can't check whether there actually is an issue here, so I'll close this out. Note that typically the color conversion based on classroom techniques is done with cv2 and not matplotlib, so that is also likely part of the reason.

**Closed by mvirgo** 2018-11-26 17:39 UTC
Labels: in progress
